# Automatically generated list of subreddit start URLs. Run the subreddit_list_gen spider to get started.
START_URLS = [
    'https://www.reddit.com/r/Home/',
    'https://www.reddit.com/r/AskReddit/',
    'https://www.reddit.com/r/NoStupidQuestions/',
    'https://www.reddit.com/r/BaldursGate3/',
    'https://www.reddit.com/r/facepalm/',
    'https://www.reddit.com/r/interestingasfuck/',
    'https://www.reddit.com/r/Damnthatsinteresting/',
    'https://www.reddit.com/r/LivestreamFail/',
    'https://www.reddit.com/r/pics/',
    'https://www.reddit.com/r/Palworld/',
    'https://www.reddit.com/r/AmItheAsshole/',
    'https://www.reddit.com/r/mildlyinfuriating/',
    'https://www.reddit.com/r/Piracy/',
    'https://www.reddit.com/r/PeterExplainsTheJoke/',
    'https://www.reddit.com/r/BaldursGate3/',
    'https://www.reddit.com/r/facepalm/',
    'https://www.reddit.com/r/interestingasfuck/',
    'https://www.reddit.com/r/Damnthatsinteresting/',
    'https://www.reddit.com/r/LivestreamFail/',
    'https://www.reddit.com/r/pics/',
]