# credit to datawookie for this script

NAMES = [
    "peter",
    "lois",
    "brian",
    "stewie",
    "meg",
    "chris",
    "quagmire",
    "joe",
    "cleveland",
    "herbert",
    "vinny",
    "homer",
    "marge",
    "lisa",
    "bart",
    "maggie"
]

WARNING = "# Generated by create-proxies script.\n\n"

# Generate docker-compose.yml.
with open("docker-compose.yml", "w") as f:
    f.write(WARNING)
    f.write("services:\n")

    for index, name in enumerate(NAMES):
        f.write(f"  tor-{name}:\n")
        f.write(f"    container_name: 'tor-{name}'\n")
        f.write("    image: 'pickapp/tor-proxy:latest'\n")
        f.write("    ports:\n")
        f.write(f"      - '{9990+index}:8888'\n")
        f.write("    environment:\n")
        f.write("      - IP_CHANGE_SECONDS=60\n")
        f.write("    restart: always\n")

# Generate proxy_list.txt.
with open("proxy_list.txt", "w") as f:
    f.write(WARNING)

    for index, name in enumerate(NAMES):
        f.write(f"http://127.0.0.1:{9990+index}\n")
